[package]
name = "class11_02"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "math"

[dependencies]
uniffi = { version = "0.28.0" }

[build-dependencies]
uniffi = { version = "0.28.0", features = [ "build" ] }
