version: '3'
services:
  kiloath:
      # Note that the path of the Dockerfile and context is relative to the *primary*
      # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
      # array). The sample below assumes your primary file is in the root of your project.
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/workspaces:cached
      # command: /bin/sh -c "while sleep 1000; do :; done"